Update amul-stock-check.yml

diff --git a/.github/workflows/amul-stock-check.yml b/.github/workflows/amul-stock-check.yml
--- a/.github/workflows/amul-stock-check.yml
+++ b/.github/workflows/amul-stock-check.yml
@@ -23,11 +23,17 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
-      - name: Install Firefox
+      - name: Setup Firefox
+        uses: browser-actions/setup-firefox@v1
+        with:
+          firefox-version: 'latest' # Or a specific version like '100.0' or 'latest-esr'
+
+      - name: Verify Firefox installation
         run: |
-          sudo add-apt-repository -y ppa:mozillateam/ppa
-          sudo apt-get update
-          sudo apt-get install -y firefox
+          firefox --version
+          pwd
+          which firefox || echo "firefox not found"
+        
 
       - name: Install Geckodriver
         run: |
